### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [brown/snappy#1]
Please consider adding :description, :author and :license information to your ASDF system. This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by brown** [comment]
The ASDF system file already contains author, description, and license information.
Did I include them incorrectly?  Are they in the wrong format?  Please take a look at
https://github.com/brown/snappy/blob/master/snappy.asd
and let me know what I should change.  Thanks!

**Comment by hydandata** [comment]
Thank you for the reply. It would be great to have all systems populated with that information, but if its too much trouble, I understand. I will likely submit pull requests for projects that have it missing only from tests.
